MCU = atmega32u4

VIA_ENABLE = yes
LT0_ENABLE = yes

BOOTMAGIC_ENABLE = lite
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = yes
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = yes
KEY_LOCK_ENABLE  = yes
